#!/usr/bin/env bash
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
#  MoneyPulse — One-Click Deploy
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
#  Usage:
#    curl -fsSL https://raw.githubusercontent.com/ManikantaR/MoneyPulse/main/scripts/deploy.sh | bash
#    — or —
#    git clone https://github.com/ManikantaR/MoneyPulse.git && cd MoneyPulse && bash scripts/deploy.sh
#
#  What this does:
#    1. Clones repo (if not already cloned)
#    2. Generates secure .env with random passwords
#    3. Creates data directories
#    4. Builds & starts all containers (postgres, redis, api, web, pdf-parser, backup)
#    5. Waits for healthy services
#    6. Optionally enables Ollama AI categorization
#    7. Prints access URL
#
#  Flags:
#    --with-ai    Enable Ollama AI categorization
#    --data-dir   Custom data directory (default: ~/moneypulse-data)
#    --port       Web UI port (default: 3000)
#    --api-port   API port (default: 4000)
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
set -euo pipefail

# ── Colors ────────────────────────────────────────────────
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
BOLD='\033[1m'
NC='\033[0m'

log()  { echo -e "${GREEN}✓${NC} $*"; }
info() { echo -e "${BLUE}→${NC} $*"; }
warn() { echo -e "${YELLOW}⚠${NC} $*"; }
err()  { echo -e "${RED}✗${NC} $*" >&2; }
die()  { err "$@"; exit 1; }

# ── Defaults ──────────────────────────────────────────────
WITH_AI=false
DATA_DIR="$HOME/moneypulse-data"
WEB_PORT=3000
API_PORT=4000
REPO_URL="https://github.com/ManikantaR/MoneyPulse.git"

# ── Parse flags ───────────────────────────────────────────
while [[ $# -gt 0 ]]; do
  case "$1" in
    --with-ai)   WITH_AI=true; shift ;;
    --data-dir)  DATA_DIR="$2"; shift 2 ;;
    --port)      WEB_PORT="$2"; shift 2 ;;
    --api-port)  API_PORT="$2"; shift 2 ;;
    -h|--help)
      echo "Usage: $0 [--with-ai] [--data-dir DIR] [--port PORT] [--api-port PORT]"
      exit 0 ;;
    *) die "Unknown option: $1" ;;
  esac
done

# ── Banner ────────────────────────────────────────────────
echo ""
echo -e "${BOLD}${CYAN}╔══════════════════════════════════════════╗${NC}"
echo -e "${BOLD}${CYAN}║     💰 MoneyPulse — One-Click Deploy    ║${NC}"
echo -e "${BOLD}${CYAN}╚══════════════════════════════════════════╝${NC}"
echo ""

# ── Detect container runtime ─────────────────────────────
COMPOSE_CMD=""
if command -v docker-compose &>/dev/null; then
  COMPOSE_CMD="docker-compose"
elif command -v docker &>/dev/null && docker compose version &>/dev/null 2>&1; then
  COMPOSE_CMD="docker compose"
elif command -v podman-compose &>/dev/null; then
  COMPOSE_CMD="podman-compose"
else
  die "No container runtime found. Install Docker or Podman first."
fi
log "Container runtime: ${BOLD}${COMPOSE_CMD}${NC}"

# ── Check git ─────────────────────────────────────────────
command -v git &>/dev/null || die "git is required but not installed."

# ── Clone repo if needed ─────────────────────────────────
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_DIR=""

# Check if we're already inside the repo
if [[ -f "$SCRIPT_DIR/../docker-compose.yml" ]]; then
  REPO_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
  info "Using existing repo at ${BOLD}${REPO_DIR}${NC}"
else
  # Running via curl pipe — clone fresh
  CLONE_TARGET="$HOME/MoneyPulse"
  if [[ -d "$CLONE_TARGET/.git" ]]; then
    info "Repo already exists at $CLONE_TARGET — pulling latest..."
    cd "$CLONE_TARGET" && git pull --ff-only
  else
    info "Cloning MoneyPulse..."
    git clone "$REPO_URL" "$CLONE_TARGET"
  fi
  REPO_DIR="$CLONE_TARGET"
fi
cd "$REPO_DIR"
log "Working directory: ${BOLD}${REPO_DIR}${NC}"

# ── Generate secrets ──────────────────────────────────────
generate_secret() {
  # Works on macOS + Linux without openssl
  if command -v openssl &>/dev/null; then
    openssl rand -hex "$1"
  else
    head -c "$1" /dev/urandom | od -An -tx1 | tr -d ' \n' | head -c $(( $1 * 2 ))
  fi
}

POSTGRES_PASSWORD="$(generate_secret 24)"
REDIS_PASSWORD="$(generate_secret 16)"
JWT_SECRET="$(generate_secret 64)"
ENCRYPTION_KEY="$(generate_secret 32)"

log "Generated secure passwords & secrets"

# ── Create data directories ──────────────────────────────
info "Creating data directories at ${BOLD}${DATA_DIR}${NC}..."
mkdir -p "$DATA_DIR"/{pg,redis,uploads,watch-folder,backup,ollama}
log "Data directories ready"

# ── Generate .env ─────────────────────────────────────────
if [[ -f ".env" ]]; then
  warn ".env already exists — backing up to .env.backup.$(date +%s)"
  cp .env ".env.backup.$(date +%s)"
fi

# For containerized deployment, DATABASE_URL and REDIS_URL use service names
cat > .env <<EOF
# ── Generated by deploy.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ") ──

# Database
POSTGRES_USER=moneypulse
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
POSTGRES_DB=moneypulse
DATABASE_URL=postgresql://moneypulse:${POSTGRES_PASSWORD}@postgres:5432/moneypulse

# Redis
REDIS_URL=redis://:${REDIS_PASSWORD}@redis:6379
REDIS_PASSWORD=${REDIS_PASSWORD}

# API
PORT=4000
NODE_ENV=production
CORS_ORIGIN=http://localhost:${WEB_PORT}

# JWT
JWT_SECRET=${JWT_SECRET}
JWT_EXPIRES_IN=15m
JWT_REFRESH_EXPIRES_IN=7d

# Encryption
ENCRYPTION_KEY=${ENCRYPTION_KEY}

# Ollama AI
OLLAMA_URL=http://ollama:11434
OLLAMA_MODEL=mistral:7b

# PDF Parser
PDF_PARSER_URL=http://pdf-parser:5000

# File Storage
UPLOAD_DIR=/data/uploads
WATCH_FOLDER_DIR=/config/watch-folder
MAX_UPLOAD_SIZE_MB=50

# Next.js
NEXT_PUBLIC_API_URL=http://localhost:${API_PORT}/api
EOF

log ".env generated with secure secrets"

# ── Update docker-compose ports if non-default ────────────
COMPOSE_OVERRIDE=""
if [[ "$WEB_PORT" != "3000" || "$API_PORT" != "4000" ]]; then
  COMPOSE_OVERRIDE="docker-compose.override.yml"
  cat > "$COMPOSE_OVERRIDE" <<EOF
services:
  api:
    ports:
      - '${API_PORT}:4000'
  web:
    ports:
      - '${WEB_PORT}:3000'
EOF
  log "Port override: web=${WEB_PORT}, api=${API_PORT}"
fi

# ── Build & start containers ─────────────────────────────
echo ""
echo -e "${BOLD}Building and starting containers...${NC}"
echo -e "${BLUE}(This may take a few minutes on first run)${NC}"
echo ""

if $WITH_AI; then
  $COMPOSE_CMD --profile ai up -d --build 2>&1
else
  $COMPOSE_CMD up -d --build 2>&1
fi

log "Containers started"

# ── Wait for healthy services ─────────────────────────────
echo ""
info "Waiting for services to become healthy..."

MAX_WAIT=120
WAITED=0
while [[ $WAITED -lt $MAX_WAIT ]]; do
  # Check API health
  if curl -sf "http://localhost:${API_PORT}/api/health" >/dev/null 2>&1; then
    log "API is healthy"
    break
  fi
  sleep 3
  WAITED=$((WAITED + 3))
  printf "."
done
echo ""

if [[ $WAITED -ge $MAX_WAIT ]]; then
  warn "API did not become healthy within ${MAX_WAIT}s — check logs with: $COMPOSE_CMD logs api"
else
  log "All services healthy"
fi

# ── Pull Ollama model if AI enabled ──────────────────────
if $WITH_AI; then
  info "Pulling Ollama model (mistral:7b)... this may take a while..."
  $COMPOSE_CMD exec ollama ollama pull mistral:7b 2>&1 || warn "Ollama model pull failed — you can retry later"
  log "AI model ready"
fi

# ── Get local IP for access from other devices ────────────
LOCAL_IP=""
if command -v hostname &>/dev/null; then
  LOCAL_IP=$(hostname -I 2>/dev/null | awk '{print $1}' || true)
fi
if [[ -z "$LOCAL_IP" ]] && command -v ifconfig &>/dev/null; then
  LOCAL_IP=$(ifconfig | grep 'inet ' | grep -v '127.0.0.1' | head -1 | awk '{print $2}')
fi

# ── Print success banner ─────────────────────────────────
echo ""
echo -e "${BOLD}${GREEN}╔══════════════════════════════════════════╗${NC}"
echo -e "${BOLD}${GREEN}║       ✅ MoneyPulse is running!          ║${NC}"
echo -e "${BOLD}${GREEN}╚══════════════════════════════════════════╝${NC}"
echo ""
echo -e "  ${BOLD}Web UI:${NC}      http://localhost:${WEB_PORT}"
if [[ -n "$LOCAL_IP" ]]; then
  echo -e "  ${BOLD}Network:${NC}     http://${LOCAL_IP}:${WEB_PORT}"
fi
echo -e "  ${BOLD}API:${NC}         http://localhost:${API_PORT}/api"
echo -e "  ${BOLD}Health:${NC}      http://localhost:${API_PORT}/api/health"
echo ""
echo -e "  ${BOLD}Data:${NC}        ${DATA_DIR}"
echo -e "  ${BOLD}AI:${NC}          $($WITH_AI && echo 'Enabled (Ollama)' || echo 'Disabled (use --with-ai to enable)')"
echo ""
echo -e "  ${CYAN}Useful commands:${NC}"
echo -e "    ${BOLD}Logs:${NC}        $COMPOSE_CMD logs -f"
echo -e "    ${BOLD}Stop:${NC}        $COMPOSE_CMD down"
echo -e "    ${BOLD}Restart:${NC}     $COMPOSE_CMD restart"
echo -e "    ${BOLD}Update:${NC}      git pull && $COMPOSE_CMD up -d --build"
echo ""
echo -e "  ${YELLOW}First time?${NC} Open the Web UI and create your account."
echo -e "  Then go to ${BOLD}Accounts${NC} → add your bank, and ${BOLD}import CSV${NC} statements."
echo ""
